# Generated by Django 4.2.30 on 2026-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_store_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Project screenshot or logo (recommended: 800x500px)', null=True, upload_to='projects/'),
        ),
    ]
